title: Bo & Co
email: work@boandco.studio
description: "Bo & Co is an award winning design + development studio based out of Manotick, Canada."
keywords: "Award winning, design, development, studio, freelance, Canada, for hire, shopify, blog, website, squarespace"
author: Connell McCarthy