title: Bo & Co
email: work@boandco.studio
description: "Bo & Co is a full-service creative studio that specializes in blending art and technology to create captivating digital experiences."
keywords: "Award winning, design, development, studio, freelance, Canada, for hire, shopify, blog, website, squarespace"
author: Connell McCarthy
domain: boandco.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://boandco.studio   # the base hostname and protocol for your site, e.g. http://example.com